title: Building The Longhand Archive
description: How a solo archival system gets built in public
url: https://longhandarchive.github.io

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

author:
  name: Andrew Allen
  url: https://andrewallen.uk/

permalink: /posts/:title/

defaults:
  - scope:
      path: "_pages"
    values:
      layout: default
      permalink: /:title/
  - scope:
      path: "_posts"
    values:
      layout: default

show_downloads: false
